// Empresas auspiciantes de MMA en Ecuador (módulo del Estudiante 2)
export const auspiciantes = [
  {
    id: "s1",
    nombre: "Pilsener Sports",
    industria: "Bebidas",
    montoUSD: 5000,
    ciudad: "Quito",
    descripcion: "Patrocinador histórico del deporte ecuatoriano.",
    lat: -0.1807,
    lng: -78.4678,
  },
  {
    id: "s2",
    nombre: "Marathon Sports",
    industria: "Ropa deportiva",
    montoUSD: 3500,
    ciudad: "Quito",
    descripcion: "Equipamiento y ropa oficial para atletas.",
    lat: -0.1763,
    lng: -78.4854,
  },
  {
    id: "s3",
    nombre: "Banco Pichincha Impulsa",
    industria: "Banca",
    montoUSD: 8000,
    ciudad: "Quito",
    descripcion: "Programa de becas para deportistas de élite.",
    lat: -0.2086,
    lng: -78.4949,
  },
  {
    id: "s4",
    nombre: "Toni Fit",
    industria: "Alimentos",
    montoUSD: 2500,
    ciudad: "Guayaquil",
    descripcion: "Nutrición deportiva para alto rendimiento.",
    lat: -2.1709,
    lng: -79.9224,
  },
  {
    id: "s5",
    nombre: "Claro Sports EC",
    industria: "Telecomunicaciones",
    montoUSD: 6500,
    ciudad: "Guayaquil",
    descripcion: "Transmisión y difusión de eventos deportivos.",
    lat: -2.1538,
    lng: -79.8862,
  },
  {
    id: "s6",
    nombre: "Cervecería Artesanal Cuenca",
    industria: "Bebidas",
    montoUSD: 1800,
    ciudad: "Cuenca",
    descripcion: "Apoyo al talento local del Azuay.",
    lat: -2.8974,
    lng: -79.0116,
  },
];
