// Rivales y venues (adaptado de mm-fight/src/lib/data.ts) — Estudiante 3
export const rivales = [
  {
    id: "f1",
    nombre: "Marlon Vera",
    apodo: "Chito",
    gimnasio: "Team Oyama",
    ciudad: "Chone",
    categoria: "Gallo",
    estilo: "Mixto",
    nivel: "Pro",
    record: "23-8-1",
    poder: 92,
    grappling: 88,
    cardio: 95,
    emoji: "🐍",
  },
  {
    id: "f2",
    nombre: "Andrés Silva",
    apodo: "La Víbora",
    gimnasio: "Iron Core Syndicate",
    ciudad: "Guayaquil",
    categoria: "Ligero",
    estilo: "Striker",
    nivel: "Pro",
    record: "14-2-0",
    poder: 96,
    grappling: 74,
    cardio: 88,
    emoji: "⚡",
  },
  {
    id: "f3",
    nombre: "Diego Almeida",
    apodo: "El Toro",
    gimnasio: "Guayas Warriors Elite",
    ciudad: "Quito",
    categoria: "Welter",
    estilo: "Grappler",
    nivel: "Pro",
    record: "18-3-0",
    poder: 78,
    grappling: 97,
    cardio: 90,
    emoji: "🐂",
  },
  {
    id: "f4",
    nombre: "Luis Caicedo",
    apodo: "El Cañón",
    gimnasio: "Iron Core Syndicate",
    ciudad: "Guayaquil",
    categoria: "Pesado",
    estilo: "Striker",
    nivel: "Amateur",
    record: "9-1-0 (Am)",
    poder: 98,
    grappling: 62,
    cardio: 82,
    emoji: "💣",
  },
  {
    id: "f5",
    nombre: "Carlos Morán",
    apodo: "El Rayo",
    gimnasio: "Azuay Fight Club",
    ciudad: "Cuenca",
    categoria: "Ligero",
    estilo: "Mixto",
    nivel: "Pro",
    record: "11-4-1",
    poder: 85,
    grappling: 83,
    cardio: 87,
    emoji: "🌩️",
  },
  {
    id: "f6",
    nombre: "Sebastián Reyes",
    apodo: "El Fantasma",
    gimnasio: "Team Oyama",
    ciudad: "Quito",
    categoria: "Mediano",
    estilo: "Grappler",
    nivel: "Amateur",
    record: "12-0-1 (Am)",
    poder: 75,
    grappling: 94,
    cardio: 91,
    emoji: "👻",
  },
];

export const venues = [
  {
    id: "v1",
    nombre: "Coliseo Voltaire Paladines Polo",
    ciudad: "Guayaquil",
    capacidad: 8000,
    lat: -2.1846,
    lng: -79.8963,
  },
  {
    id: "v2",
    nombre: "Arena Quito",
    ciudad: "Quito",
    capacidad: 12000,
    lat: -0.2295,
    lng: -78.5243,
  },
  {
    id: "v3",
    nombre: "Coliseo General Rumiñahui",
    ciudad: "Quito",
    capacidad: 14000,
    lat: -0.2103,
    lng: -78.4923,
  },
  {
    id: "v4",
    nombre: "Coliseo Jorge Calvache",
    ciudad: "Cuenca",
    capacidad: 5000,
    lat: -2.9012,
    lng: -78.9997,
  },
];

export const fechasPropuestas = ["2026-08-15", "2026-08-29", "2026-09-12"];
